DROP TABLE IF EXISTS users;

CREATE TYPE offset AS ENUM (
  'UTC 0',
  'EST -5',
  'CST -6',
  'MST -7'
  'PST -8'
);

CREATE TABLE users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username TEXT NOT NULL,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT NOT NULL,
  password TEXT NOT NULL,
  about_me TEXT,
  avatar_link TEXT,
  timezone offset DEFAULT 'UTC 0' NOT NULL,
  date_created TIMESTAMPTZ DEFAULT now() NOT NULL,
  date_modified TIMESTAMPTZ DEFAULT now()
);