DROP TABLE IF EXISTS timezone;

/*https://www.postgresql.org/docs/7.2/timezones.html*/
CREATE TABLE timezone (
    timezoneId INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    zoneName TEXT NOT NULL DEFAULT 'UTC',
    zoneOffset TEXT NOT NULL DEFAULT '+00:00',
    zoneDesc TEXT NOT NULL DEFAULT 'Universal Time, Coordinated'
);

/* timezone offset DEFAULT 'UTC 0' NOT NULL,

CREATE TYPE offset AS ENUM (
  'UTC 0',
  'EST -5',
  'CST -6',
  'MST -7'
  'PST -8'
); */