DROP TABLE IF EXISTS timezone;

/*https://www.postgresql.org/docs/7.2/timezones.html*/
CREATE TABLE timezone (
    timezoneId INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    zoneName TEXT NOT NULL DEFAULT 'UTC',
    zoneOffset TEXT NOT NULL DEFAULT '+00:00',
    zoneDesc TEXT NOT NULL DEFAULT 'Universal Time, Coordinated'
);