DROP TABLE IF EXISTS timezone;

/*https://www.postgresql.org/docs/7.2/timezones.html*/
CREATE TABLE timezone (
    timezoneid INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    zonename TEXT NOT NULL DEFAULT 'UTC',
    zoneoffset TEXT NOT NULL DEFAULT '+00:00',
    zonedesc TEXT NOT NULL DEFAULT 'Universal Time, Coordinated'
);