DROP TABLE IF EXISTS week;

CREATE TABLE week (
    weekId INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    sun_am_id INTEGER REFERENCES sun_AM(sun_AM_Id) NOT NULL, 
    sun_pm_id INTEGER REFERENCES sun_PM(sun_PM_Id) NOT NULL,
    mon_am_id INTEGER REFERENCES mon_AM(mon_AM_Id) NOT NULL,
    mon_pm_id INTEGER REFERENCES mon_PM(mon_PM_Id) NOT NULL,
    tue_am_id INTEGER REFERENCES tue_AM(tue_AM_Id) NOT NULL,
    tue_pm_id INTEGER REFERENCES tue_PM(tue_PM_Id) NOT NULL,
    wed_am_id INTEGER REFERENCES wed_AM(wed_AM_Id) NOT NULL,
    wed_pm_id INTEGER REFERENCES wed_PM(wed_PM_Id) NOT NULL,
    thu_am_id INTEGER REFERENCES thu_AM(thu_AM_Id) NOT NULL,
    thu_pm_id INTEGER REFERENCES thu_PM(thu_PM_Id) NOT NULL,
    fri_am_id INTEGER REFERENCES fri_AM(fri_AM_Id) NOT NULL,
    fri_pm_id INTEGER REFERENCES fri_PM(fri_PM_Id) NOT NULL,
    sat_am_id INTEGER REFERENCES sat_AM(sat_AM_Id) NOT NULL,
    sat_pm_id INTEGER REFERENCES sat_PM(sat_PM_Id) NOT NULL,
    week_type TEXT NOT NULL, 
);