DROP TABLE IF EXISTS users;

CREATE TABLE users (
	userId INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
	username TEXT NOT NULL UNIQUE, 
	firstname TEXT NOT NULL, 
	lastname TEXT NOT NULL, 
    email TEXT NOT NULL,
	password TEXT NOT NULL, 
	aboutme TEXT, 
	avatar TEXT, 
	date_created TIMESTAMPTZ NOT NULL DEFAULT now(),
    date_modified TIMESTAMPTZ DEFAULT now(),
	timezone INTEGER REFERENCES timezone(timezoneId),
	weekId INTEGER REFERENCES weekId ON DELETE CASCADE NOT NULL
);