DROP TABLE IF EXISTS group_members;

CREATE TYPE access_level AS ENUM (
  'Founder',
  'Admin',
  'Member',
  'Applicant'
);

CREATE TABLE group_members (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  group_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  member_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  member_level access_level DEFAULT 'Applicant' NOT NULL,
  join_date TIMESTAMPTZ DEFAULT now() NOT NULL
);

ALTER TABLE groups ADD COLUMN members INTEGER REFERENCES group_members(id) NOT NULL;